FROM ckan2_8_harvest:latest

ENV CKAN_HOME /usr/lib/ckan

ARG POSTGRES_USER
ARG DB_CKAN_USER
ARG DB_CKAN_PASSWORD
ARG DB_CKAN_DB
ARG DB_PYCSW_DB
ARG CKAN_SITE_URL

WORKDIR /usr/lib/ckan/

# Configure ckan app
COPY docker/webserver/config/configure_app.sh /configure_app.sh
RUN chmod +x /configure_app.sh && cd / && ./configure_app.sh

RUN ckan-pip install -e "git+https://github.com/GSA/ckanext-geodatagov@80b72945926134f0d9d3fb59741284332672cac4#egg=ckanext_geodatagov" && \
  ckan-pip install -r $CKAN_HOME/src/ckanext-geodatagov/pip-requirements.txt && \
  ckan-pip install -e "git+https://github.com/ckan/ckanext-spatial.git#egg=ckanext-spatial" && \
  ckan-pip install -r $CKAN_HOME/src/ckanext-spatial/pip-requirements.txt

COPY docker/webserver/config/configure_geodatagov.sh /configure_geodatagov.sh

CMD ["/wait-for-it.sh", "db:5432", "--", "/start_app.sh", "/configure_geodatagov.sh"]
