FROM ckan2_8:latest

ENV CKAN_HOME /usr/lib/ckan

WORKDIR /usr/lib/ckan/

RUN ckan-pip install -e git+https://github.com/datagovuk/ckanext-report.git#egg=ckanext-report
  # ckan-pip install -r $CKAN_HOME/src/ckanext-ga-report/requirements.txt

COPY docker/webserver/config/configure_report.sh /configure_report.sh

CMD ["/wait-for-it.sh", "db:5432", "--", "/configure_app.sh", "/configure_report.sh"]
